import type { SimpleIcon } from 'simple-icons'
import {
  siAngular, siAnsible, siApachecassandra, siApachecouchdb, siApachekafka, siApachepulsar, siArgo, siBitbucket, siBun,
  siC, siCircleci, siClickhouse, siCloudflare, siCloudfoundry, siCockroachlabs, siCouchbase, siCplusplus,
  siDart, siDatadog, siDeno, siDigitalocean, siDjango, siDocker, siDuckdb, siDynatrace,
  siEclipsemosquitto, siElasticsearch, siElastic, siElixir, siEnvoyproxy, siErlang,
  siFastapi, siFirebase, siFlutter, siFlux, siFlydotio,
  siGithub, siGithubactions, siGitlab, siGo, siGooglecloud, siGrafana,
  siHaskell, siHelm, siHetzner, siInfluxdb, siIstio, siJaeger, siJavascript, siJenkins,
  siKibana, siKotlin, siKubernetes, siLaravel, siLinux, siLogstash, siLua,
  siMariadb, siMongodb, siMysql, siNatsdotio, siNeo4j, siNestjs, siNetlify, siNewrelic, siNextdotjs,
  siNginx, siNodedotjs, siNomad, siNuxt, siOpentelemetry, siOpenjdk, siOpenstack, siOvh,
  siPacker, siPhp, siPlanetscale, siPodman, siPostgresql, siPrisma, siPrometheus, siPulumi, siPython,
  siRabbitmq, siRailway, siRancher, siReact, siRedis, siRedhatopenshift, siRender, siRuby, siRubyonrails, siRust,
  siScala, siSentry, siSnowflake, siSocketdotio, siSplunk, siSpring, siSqlite, siSupabase, siSvelte, siSwift,
  siTerraform, siTraefikproxy, siTravisci, siTypescript, siVagrant, siVault, siVercel, siVuedotjs,
} from 'simple-icons'

export type TechnologyCategory = 'databases' | 'devops' | 'messaging' | 'observability' | 'cloud' | 'runtimes'
export type Technology = { id: string; name: string; category: TechnologyCategory; icon: SimpleIcon }

export const technologyCategories: { id: TechnologyCategory; label: string; fr: string }[] = [
  { id: 'databases', label: 'Databases', fr: 'Bases de données' },
  { id: 'devops', label: 'DevOps & infrastructure', fr: 'DevOps & infrastructure' },
  { id: 'messaging', label: 'Messaging', fr: 'Messagerie' },
  { id: 'observability', label: 'Observability', fr: 'Observabilité' },
  { id: 'cloud', label: 'Cloud & edge', fr: 'Cloud & edge' },
  { id: 'runtimes', label: 'Languages & frameworks', fr: 'Langages & frameworks' },
]

const technology = (id: string, name: string, category: TechnologyCategory, icon: SimpleIcon): Technology => ({ id, name, category, icon })

export const technologies: Technology[] = [
  technology('postgresql', 'PostgreSQL', 'databases', siPostgresql), technology('mongodb', 'MongoDB', 'databases', siMongodb), technology('cassandra', 'Cassandra', 'databases', siApachecassandra), technology('redis', 'Redis', 'databases', siRedis), technology('mysql', 'MySQL', 'databases', siMysql), technology('mariadb', 'MariaDB', 'databases', siMariadb), technology('sqlite', 'SQLite', 'databases', siSqlite), technology('elasticsearch', 'Elasticsearch', 'databases', siElasticsearch), technology('clickhouse', 'ClickHouse', 'databases', siClickhouse), technology('cockroachdb', 'CockroachDB', 'databases', siCockroachlabs), technology('couchbase', 'Couchbase', 'databases', siCouchbase), technology('couchdb', 'CouchDB', 'databases', siApachecouchdb), technology('duckdb', 'DuckDB', 'databases', siDuckdb), technology('influxdb', 'InfluxDB', 'databases', siInfluxdb), technology('neo4j', 'Neo4j', 'databases', siNeo4j), technology('snowflake', 'Snowflake', 'databases', siSnowflake), technology('supabase', 'Supabase', 'databases', siSupabase), technology('firebase', 'Firebase', 'databases', siFirebase), technology('planetscale', 'PlanetScale', 'databases', siPlanetscale), technology('prisma', 'Prisma', 'databases', siPrisma),
  technology('docker', 'Docker', 'devops', siDocker), technology('kubernetes', 'Kubernetes', 'devops', siKubernetes), technology('github', 'GitHub', 'devops', siGithub), technology('github-actions', 'GitHub Actions', 'devops', siGithubactions), technology('gitlab', 'GitLab', 'devops', siGitlab), technology('bitbucket', 'Bitbucket', 'devops', siBitbucket), technology('jenkins', 'Jenkins', 'devops', siJenkins), technology('circleci', 'CircleCI', 'devops', siCircleci), technology('travis-ci', 'Travis CI', 'devops', siTravisci), technology('terraform', 'Terraform', 'devops', siTerraform), technology('pulumi', 'Pulumi', 'devops', siPulumi), technology('ansible', 'Ansible', 'devops', siAnsible), technology('helm', 'Helm', 'devops', siHelm), technology('argo', 'Argo', 'devops', siArgo), technology('flux', 'Flux', 'devops', siFlux), technology('vault', 'Vault', 'devops', siVault), technology('nomad', 'Nomad', 'devops', siNomad), technology('packer', 'Packer', 'devops', siPacker), technology('vagrant', 'Vagrant', 'devops', siVagrant), technology('rancher', 'Rancher', 'devops', siRancher), technology('openshift', 'OpenShift', 'devops', siRedhatopenshift), technology('podman', 'Podman', 'devops', siPodman), technology('istio', 'Istio', 'devops', siIstio), technology('envoy', 'Envoy', 'devops', siEnvoyproxy), technology('traefik', 'Traefik Proxy', 'devops', siTraefikproxy), technology('nginx', 'NGINX', 'devops', siNginx), technology('linux', 'Linux', 'devops', siLinux),
  technology('kafka', 'Apache Kafka', 'messaging', siApachekafka), technology('pulsar', 'Apache Pulsar', 'messaging', siApachepulsar), technology('rabbitmq', 'RabbitMQ', 'messaging', siRabbitmq), technology('nats', 'NATS', 'messaging', siNatsdotio), technology('mosquitto', 'Eclipse Mosquitto', 'messaging', siEclipsemosquitto), technology('socketio', 'Socket.IO', 'messaging', siSocketdotio),
  technology('prometheus', 'Prometheus', 'observability', siPrometheus), technology('grafana', 'Grafana', 'observability', siGrafana), technology('opentelemetry', 'OpenTelemetry', 'observability', siOpentelemetry), technology('datadog', 'Datadog', 'observability', siDatadog), technology('dynatrace', 'Dynatrace', 'observability', siDynatrace), technology('new-relic', 'New Relic', 'observability', siNewrelic), technology('sentry', 'Sentry', 'observability', siSentry), technology('jaeger', 'Jaeger', 'observability', siJaeger), technology('elastic', 'Elastic', 'observability', siElastic), technology('kibana', 'Kibana', 'observability', siKibana), technology('logstash', 'Logstash', 'observability', siLogstash), technology('splunk', 'Splunk', 'observability', siSplunk),
  technology('google-cloud', 'Google Cloud', 'cloud', siGooglecloud), technology('cloudflare', 'Cloudflare', 'cloud', siCloudflare), technology('digitalocean', 'DigitalOcean', 'cloud', siDigitalocean), technology('openstack', 'OpenStack', 'cloud', siOpenstack), technology('cloud-foundry', 'Cloud Foundry', 'cloud', siCloudfoundry), technology('hetzner', 'Hetzner', 'cloud', siHetzner), technology('ovhcloud', 'OVHcloud', 'cloud', siOvh), technology('vercel', 'Vercel', 'cloud', siVercel), technology('netlify', 'Netlify', 'cloud', siNetlify), technology('render', 'Render', 'cloud', siRender), technology('flyio', 'Fly.io', 'cloud', siFlydotio), technology('railway', 'Railway', 'cloud', siRailway),
  technology('javascript', 'JavaScript', 'runtimes', siJavascript), technology('typescript', 'TypeScript', 'runtimes', siTypescript), technology('react', 'React', 'runtimes', siReact), technology('vue', 'Vue.js', 'runtimes', siVuedotjs), technology('angular', 'Angular', 'runtimes', siAngular), technology('svelte', 'Svelte', 'runtimes', siSvelte), technology('nextjs', 'Next.js', 'runtimes', siNextdotjs), technology('nuxt', 'Nuxt', 'runtimes', siNuxt), technology('nodejs', 'Node.js', 'runtimes', siNodedotjs), technology('deno', 'Deno', 'runtimes', siDeno), technology('bun', 'Bun', 'runtimes', siBun), technology('python', 'Python', 'runtimes', siPython), technology('django', 'Django', 'runtimes', siDjango), technology('fastapi', 'FastAPI', 'runtimes', siFastapi), technology('go', 'Go', 'runtimes', siGo), technology('rust', 'Rust', 'runtimes', siRust), technology('php', 'PHP', 'runtimes', siPhp), technology('laravel', 'Laravel', 'runtimes', siLaravel), technology('ruby', 'Ruby', 'runtimes', siRuby), technology('rails', 'Ruby on Rails', 'runtimes', siRubyonrails), technology('kotlin', 'Kotlin', 'runtimes', siKotlin), technology('openjdk', 'OpenJDK', 'runtimes', siOpenjdk), technology('spring', 'Spring', 'runtimes', siSpring), technology('swift', 'Swift', 'runtimes', siSwift), technology('dart', 'Dart', 'runtimes', siDart), technology('flutter', 'Flutter', 'runtimes', siFlutter), technology('c', 'C', 'runtimes', siC), technology('cpp', 'C++', 'runtimes', siCplusplus), technology('scala', 'Scala', 'runtimes', siScala), technology('elixir', 'Elixir', 'runtimes', siElixir), technology('erlang', 'Erlang', 'runtimes', siErlang), technology('lua', 'Lua', 'runtimes', siLua), technology('haskell', 'Haskell', 'runtimes', siHaskell), technology('nest', 'NestJS', 'runtimes', siNestjs),
]

export const getTechnology = (id?: string) => technologies.find(item => item.id === id)
