import { type PointerEvent, type ReactNode, type RefObject, useEffect, useMemo, useRef, useState } from 'react'
import { Activity, AlertTriangle, ArrowLeftRight, BarChart3, Blocks, Box, Boxes, ChevronDown, CircuitBoard, ClipboardPaste, Code2, Copy, Cpu, Database, Download, FileText, Focus, Gauge, Inbox, Layers3, LayoutGrid, LoaderCircle, Maximize, Network, PanelTop, Palette, Plus, Route, Sparkles, Square, Trash2, Truck, Users, Workflow, Zap, ZoomIn, ZoomOut, type LucideIcon } from 'lucide-react'
import { useDiagram } from '../application/useDiagram'
import { arrowAnimations, nodeAnimations } from '../domain/animationCatalog'
import { cloneDiagram, cloneDiagramWithTheme, diagramTemplates } from '../domain/diagramTemplates'
import { getTechnology, technologies, technologyCategories } from '../domain/technologyCatalog'
import { electronicCategories, electronicComponents, getElectronicComponent } from '../domain/electronicCatalog'
import type { AppTheme, Diagram, DiagramEdge, DiagramNode, EdgeRoute, NodeKind, Side } from '../domain/diagram'
import { usePreferences } from '../../preferences/application/usePreferences'
import { cn } from '../../../shared/lib/cn'
import { downloadDiagramArtifacts } from '../../../shared/lib/gifExporter'

const colors = ['#10151d', '#18243a', '#231a3f', '#2b0818', '#18332a', '#0c3438', '#243257', '#693743']
const kinds: { id: NodeKind; label: string; fr: string; icon: LucideIcon }[] = [
  { id: 'card', label: 'Card', fr: 'Carte', icon: Box }, { id: 'service', label: 'Service', fr: 'Service', icon: Cpu }, { id: 'group', label: 'Boundary', fr: 'Groupe', icon: LayoutGrid }, { id: 'platform', label: 'Platform', fr: 'Plateforme', icon: PanelTop },
  { id: 'database', label: 'Data store', fr: 'Données', icon: Database }, { id: 'technology', label: 'Technology', fr: 'Technologie', icon: Blocks }, { id: 'electronic', label: 'Electronics', fr: 'Électronique', icon: CircuitBoard }, { id: 'actor', label: 'Actor', fr: 'Acteur', icon: Users }, { id: 'note', label: 'Action', fr: 'Action', icon: Zap }, { id: 'metric', label: 'Metric', fr: 'Métrique', icon: Activity },
]
const themes: { id: AppTheme; label: string; fr: string }[] = [
  { id: 'midnight', label: 'Midnight', fr: 'Nuit' }, { id: 'blueprint', label: 'Blueprint', fr: 'Plan bleu' }, { id: 'electric', label: 'Electric', fr: 'Électrique' }, { id: 'light', label: 'Paper', fr: 'Papier' },
]
const iconMap: Record<string, LucideIcon> = { activity: Activity, alert: AlertTriangle, warning: AlertTriangle, box: Box, boxes: Boxes, chart: BarChart3, code: Code2, cpu: Cpu, database: Database, file: FileText, focus: Focus, gauge: Gauge, inbox: Inbox, layers: Layers3, network: Network, panels: PanelTop, route: Route, sparkles: Sparkles, truck: Truck, users: Users, workflow: Workflow, zap: Zap }

export function EditorPage() {
  const state = useDiagram(), prefs = usePreferences()
  const { diagram, selected, selectedId, setSelectedId, selectedEdge, selectedEdgeId, setSelectedEdgeId, removeSelectedEdge, removeSelectedNode, moveNode, resizeNode, addNode, copySelectedNode, pasteNode, canPaste, connect, arrowAnimation, setArrowAnimation, setNodeAnimation } = state
  const [zoom, setZoom] = useState(.72), [libraryOpen, setLibraryOpen] = useState(true), [addOpen, setAddOpen] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [exportError, setExportError] = useState<string | null>(null)
  const stageRef = useRef<HTMLDivElement>(null)
  const [open, setOpen] = useState<Record<string, boolean>>({ properties: true, style: true, animation: false, arrows: true })
  const changeTheme = (theme: AppTheme) => { prefs.setTheme(theme); state.setDiagram(current => ({ ...current, background: theme })) }
  const exportArtifacts = async () => {
    if (exporting) return
    setExporting(true)
    try {
      setExportError(null)
      await new Promise<void>(resolve => requestAnimationFrame(() => resolve()))
      await downloadDiagramArtifacts(diagram)
    } catch (error) {
      const fallback = prefs.locale === 'fr' ? 'Le moteur GIF est indisponible. Redémarrez le serveur Diagrammaton.' : 'The GIF renderer is unavailable. Restart the Diagrammaton server.'
      setExportError(error instanceof Error && !error.message.includes('unavailable') ? error.message : fallback)
    } finally { setExporting(false) }
  }
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (['INPUT', 'TEXTAREA', 'SELECT'].includes((event.target as HTMLElement)?.tagName)) return
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'c' && selected) { event.preventDefault(); copySelectedNode() }
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'v' && canPaste) { event.preventDefault(); pasteNode() }
      if ((event.key === 'Delete' || event.key === 'Backspace') && (selected || selectedEdge)) {
        if (selectedEdge) removeSelectedEdge(); else removeSelectedNode()
      }
      if (event.key === 'Escape') { setSelectedId(null); setLibraryOpen(false); setAddOpen(false) }
    }
    window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown)
  }, [canPaste, copySelectedNode, pasteNode, removeSelectedEdge, removeSelectedNode, selected, selectedEdge, setSelectedId])

  return <main className="studio" data-theme={diagram.background}>
    <aside className="studio-rail"><div className="studio-mark">D</div><button className={cn('rail-tool', libraryOpen && 'active')} onClick={() => setLibraryOpen(value => !value)} title="Library"><Blocks size={18} /></button><span className="rail-spacer" /><button className="avatar">CM</button></aside>
    <section className="studio-main">
      <header className="studio-topbar"><div className="document-title"><span>DIAGRAMMATON</span><input value={diagram.title} onChange={event => state.setDiagram(current => ({ ...current, title: event.target.value }))} /><small>{diagram.nodes.length} HTML components · {diagram.edges.length} connections</small></div><div className="top-actions">{exportError && <span className="export-error" role="alert">{exportError}</span>}<label className="theme-select"><Palette size={14} /><select value={diagram.background} onChange={event => changeTheme(event.target.value as AppTheme)}>{themes.map(theme => <option key={theme.id} value={theme.id}>{prefs.locale === 'fr' ? theme.fr : theme.label}</option>)}</select></label><label className="language-switch"><select value={prefs.locale} onChange={event => prefs.setLocale(event.target.value as 'en' | 'fr')}><option value="en">EN</option><option value="fr">FR</option></select></label><button className="diagram-export" disabled={exporting} onClick={exportArtifacts}>{exporting ? <LoaderCircle className="spin" size={15} /> : <Download size={15} />}<span>{exporting ? (prefs.locale === 'fr' ? 'Création…' : 'Rendering…') : (prefs.locale === 'fr' ? 'Télécharger HTML + GIF' : 'Download HTML + GIF')}</span></button></div></header>
      <div className="studio-body">
        <section className="board-panel">
          <div className="floating-toolbar"><button className={cn(libraryOpen && 'active')} onClick={() => setLibraryOpen(value => !value)}><LayoutGrid size={16} /><span>{prefs.locale === 'fr' ? 'Modèles' : 'Templates'}</span></button><i /><div className="add-wrap"><button className={cn(addOpen && 'active')} onClick={() => setAddOpen(value => !value)}><Plus size={16} /><span>{prefs.locale === 'fr' ? 'Composant' : 'Component'}</span><ChevronDown size={13} /></button>{addOpen && <div className="component-menu">{kinds.map(kind => <button key={kind.id} onClick={() => { addNode(kind.id); setAddOpen(false) }}><kind.icon size={16} /><span>{prefs.locale === 'fr' ? kind.fr : kind.label}</span></button>)}</div>}</div></div>
          {libraryOpen && <TemplateLibrary locale={prefs.locale} onClose={() => setLibraryOpen(false)} onAddTechnology={state.addTechnology} onAddElectronic={state.addElectronic} onChoose={next => { state.loadDiagram(cloneDiagramWithTheme(next, diagram.background)); setZoom(next.width > 1300 ? .68 : .76) }} />}
          <Canvas stageRef={stageRef} diagram={diagram} selectedId={selectedId} selectedEdgeId={selectedEdgeId} onSelect={setSelectedId} onSelectEdge={setSelectedEdgeId} onConnect={connect} onMove={moveNode} onResize={resizeNode} zoom={zoom} />
          <div className="board-status"><span><i />{prefs.locale === 'fr' ? 'Rendu DOM en direct' : 'Live DOM render'}</span><div className="zoom"><button onClick={() => setZoom(value => Math.max(.35, value - .1))}><ZoomOut size={15} /></button><b>{Math.round(zoom * 100)}%</b><button onClick={() => setZoom(value => Math.min(1.4, value + .1))}><ZoomIn size={15} /></button><button onClick={() => setZoom(diagram.width > 1300 ? .68 : .76)}><Maximize size={14} /></button></div></div>
        </section>
        <Inspector state={state} prefs={prefs} open={open} setOpen={setOpen} arrowAnimation={arrowAnimation} setArrowAnimation={setArrowAnimation} setNodeAnimation={setNodeAnimation} onDownload={exportArtifacts} exporting={exporting} />
      </div>
    </section>
  </main>
}

function TemplateLibrary({ locale, onClose, onChoose, onAddTechnology, onAddElectronic }: { locale: 'en' | 'fr'; onClose: () => void; onChoose: (diagram: Diagram) => void; onAddTechnology: (id: string) => void; onAddElectronic: (id: string) => void }) {
  const [query, setQuery] = useState('')
  const matching = technologies.filter(item => item.name.toLowerCase().includes(query.toLowerCase()))
  return <aside className="template-drawer">
    <div className="drawer-head"><div><span>{locale === 'fr' ? 'BIBLIOTHÈQUE' : 'LIBRARY'}</span><h2>{locale === 'fr' ? 'Compositions HTML' : 'HTML compositions'}</h2></div><button onClick={onClose}>×</button></div>
    <p>{locale === 'fr' ? 'Des structures sémantiques prêtes à adapter, inspirées des rendus éditoriaux d’Archify.' : 'Semantic structures ready to adapt, inspired by Archify’s editorial output.'}</p>
    <div className="template-list">{diagramTemplates.map(template => <button key={template.id} className={cn('template-card', template.id === 'blank' && 'blank-template')} onClick={() => onChoose(cloneDiagram(template.diagram))}><span className={`template-preview preview-${template.id}`}><i /><i /><i /><i /></span><b>{locale === 'fr' ? template.fr : template.name}</b><small>{locale === 'fr' ? template.frDescription : template.description}</small></button>)}</div>
    <div className="element-library"><span>{locale === 'fr' ? 'ÉLÉMENTS' : 'ELEMENTS'}</span><div>{kinds.map(kind => { const Icon = kind.icon; return <span key={kind.id}><Icon size={13} />{locale === 'fr' ? kind.fr : kind.label}</span> })}</div></div>
    <details className="catalog-dropdown electronic-library">
      <summary><span>{locale === 'fr' ? 'ÉLECTRONIQUE' : 'ELECTRONICS'}</span><small>{electronicComponents.length}</small><ChevronDown size={14} /></summary>
      <div className="catalog-content">{electronicCategories.map(category => <section key={category.id}><b>{locale === 'fr' ? category.fr : category.label}</b><div>{electronicComponents.filter(item => item.category === category.id).map(item => <button key={item.id} onClick={() => onAddElectronic(item.id)} title={`${locale === 'fr' ? 'Ajouter' : 'Add'} ${locale === 'fr' ? item.fr : item.name}`}><ElectronicIcon component={item.id} size={22} /><span>{locale === 'fr' ? item.fr : item.name}</span><Plus size={11} /></button>)}</div></section>)}</div>
    </details>
    <details className="catalog-dropdown technology-library">
      <summary><span>{locale === 'fr' ? 'TECHNOLOGIES' : 'TECHNOLOGIES'}</span><small>{matching.length}</small><ChevronDown size={14} /></summary>
      <div className="catalog-content"><input aria-label="Search technologies" value={query} onChange={event => setQuery(event.target.value)} placeholder={locale === 'fr' ? 'Rechercher PostgreSQL, Docker…' : 'Search PostgreSQL, Docker…'} />{technologyCategories.map(category => { const items = matching.filter(item => item.category === category.id); if (!items.length) return null; return <section key={category.id}><b>{locale === 'fr' ? category.fr : category.label}</b><div>{items.map(item => <button key={item.id} title={`${locale === 'fr' ? 'Ajouter' : 'Add'} ${item.name}`} onClick={() => onAddTechnology(item.id)}><BrandIcon technology={item.id} size={20} /><span>{item.name}</span><Plus size={11} /></button>)}</div></section> })}</div>
    </details>
  </aside>
}

function Inspector({ state, prefs, open, setOpen, arrowAnimation, setArrowAnimation, setNodeAnimation, onDownload, exporting }: { state: ReturnType<typeof useDiagram>; prefs: ReturnType<typeof usePreferences>; open: Record<string, boolean>; setOpen: React.Dispatch<React.SetStateAction<Record<string, boolean>>>; arrowAnimation: string; setArrowAnimation: (id: string) => void; setNodeAnimation: (id: string) => void; onDownload: () => void; exporting: boolean }) {
  const { diagram, selected, selectedEdge, updateNode, updateEdge, removeSelectedEdge, removeSelectedNode, copySelectedNode, pasteNode, canPaste } = state
  const toggle = (key: string) => setOpen(current => ({ ...current, [key]: !current[key] }))
  return <aside className="property-panel"><div className="property-head"><div><span>{selectedEdge ? 'CONNECTION' : selected ? 'COMPONENT' : 'DOCUMENT'}</span><b>{selectedEdge ? selectedEdge.label || `${selectedEdge.from} → ${selectedEdge.to}` : selected?.title || (prefs.locale === 'fr' ? 'Vue d’ensemble' : 'Overview')}</b></div>{(selected || selectedEdge) && <div>{selected && <><button onClick={copySelectedNode} title="Copy"><Copy size={14} /></button><button onClick={pasteNode} disabled={!canPaste} title="Paste"><ClipboardPaste size={14} /></button></>}<button onClick={selectedEdge ? removeSelectedEdge : removeSelectedNode} title="Delete"><Trash2 size={14} /></button></div>}</div><div className="property-scroll">
    {selectedEdge ? <>
      <Section title={prefs.locale === 'fr' ? 'Connexion' : 'Connection'} icon={<ArrowLeftRight size={14} />} open={open.properties} onToggle={() => toggle('properties')}><Field label={prefs.locale === 'fr' ? 'Libellé' : 'Label'}><input value={selectedEdge.label} onChange={event => updateEdge({ label: event.target.value })} placeholder="data / event / action" /></Field><Field label={prefs.locale === 'fr' ? 'Tracé' : 'Route'}><select value={selectedEdge.route ?? 'curve'} onChange={event => updateEdge({ route: event.target.value as EdgeRoute })}><option value="curve">Curve</option><option value="orthogonal">Orthogonal</option><option value="straight">Straight</option></select></Field><div className="inline-fields"><Field label={prefs.locale === 'fr' ? 'Couleur' : 'Color'}><input type="color" value={selectedEdge.color} onChange={event => updateEdge({ color: event.target.value })} /></Field><Field label={prefs.locale === 'fr' ? 'Direction' : 'Direction'}><button className="field-button" onClick={() => updateEdge({ direction: selectedEdge.direction === 'forward' ? 'both' : 'forward' })}>{selectedEdge.direction === 'both' ? '↔ Both' : '→ Forward'}</button></Field></div><label className="check-field"><input type="checkbox" checked={Boolean(selectedEdge.dashed)} onChange={event => updateEdge({ dashed: event.target.checked })} />{prefs.locale === 'fr' ? 'Ligne secondaire en pointillés' : 'Dashed secondary line'}</label></Section>
      <Section title={prefs.locale === 'fr' ? 'Mouvement du flux' : 'Flow motion'} icon={<Zap size={14} />} open={open.arrows} onToggle={() => toggle('arrows')}><div className="motion-list">{arrowAnimations.map(item => <button key={item.id} className={cn(arrowAnimation === item.id && 'active')} onClick={() => setArrowAnimation(item.id)}><span className={`line-sample sample-${item.id}`} /><b>{prefs.locale === 'fr' ? item.fr : item.name}</b></button>)}</div></Section>
    </> : selected ? <>
      <Section title={prefs.locale === 'fr' ? 'Contenu' : 'Content'} icon={<Square size={14} />} open={open.properties} onToggle={() => toggle('properties')}><Field label={prefs.locale === 'fr' ? 'Type HTML' : 'HTML type'}><select value={selected.kind} onChange={event => updateNode({ kind: event.target.value as NodeKind })}>{kinds.map(kind => <option key={kind.id} value={kind.id}>{prefs.locale === 'fr' ? kind.fr : kind.label}</option>)}</select></Field>{selected.kind === 'technology' && <Field label={prefs.locale === 'fr' ? 'Logo technologique' : 'Technology logo'}><select value={selected.technology ?? ''} onChange={event => { const technology = getTechnology(event.target.value); updateNode({ technology: technology?.id, title: technology?.name ?? selected.title, subtitle: technology?.category ?? selected.subtitle }) }}><option value="">—</option>{technologyCategories.map(category => <optgroup key={category.id} label={prefs.locale === 'fr' ? category.fr : category.label}>{technologies.filter(item => item.category === category.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</optgroup>)}</select></Field>}{selected.kind === 'electronic' && <Field label={prefs.locale === 'fr' ? 'Symbole électronique' : 'Electronic symbol'}><select value={selected.electronic ?? ''} onChange={event => { const component = getElectronicComponent(event.target.value); updateNode({ electronic: component?.id, title: prefs.locale === 'fr' ? component?.fr ?? selected.title : component?.name ?? selected.title, subtitle: component?.category ?? selected.subtitle }) }}><option value="">—</option>{electronicCategories.map(category => <optgroup key={category.id} label={prefs.locale === 'fr' ? category.fr : category.label}>{electronicComponents.filter(item => item.category === category.id).map(item => <option key={item.id} value={item.id}>{prefs.locale === 'fr' ? item.fr : item.name}</option>)}</optgroup>)}</select></Field>}<Field label={prefs.locale === 'fr' ? 'Sur-titre' : 'Eyebrow'}><input value={selected.eyebrow ?? ''} onChange={event => updateNode({ eyebrow: event.target.value })} placeholder="PLATFORM" /></Field><Field label={prefs.locale === 'fr' ? 'Titre' : 'Title'}><input value={selected.title} onChange={event => updateNode({ title: event.target.value })} /></Field><Field label={prefs.locale === 'fr' ? 'Description' : 'Description'}><textarea rows={3} value={selected.subtitle} onChange={event => updateNode({ subtitle: event.target.value })} /></Field><Field label={prefs.locale === 'fr' ? 'Badge' : 'Badge'}><input value={selected.badge ?? ''} onChange={event => updateNode({ badge: event.target.value })} placeholder="AUTOMATION" /></Field><Field label={prefs.locale === 'fr' ? 'Éléments (séparés par des virgules)' : 'Items (comma-separated)'}><input value={selected.items?.join(', ') ?? ''} onChange={event => updateNode({ items: event.target.value.split(',').map(value => value.trim()).filter(Boolean) })} /></Field></Section>
      <Section title={prefs.locale === 'fr' ? 'Style' : 'Style'} icon={<Palette size={14} />} open={open.style} onToggle={() => toggle('style')}><div className="swatches">{colors.map(color => <button key={color} className={cn(selected.color === color && 'active')} style={{ background: color }} onClick={() => updateNode({ color })} />)}</div></Section>
      <Section title={prefs.locale === 'fr' ? 'Animation' : 'Animation'} icon={<Sparkles size={14} />} open={open.animation} onToggle={() => toggle('animation')}><div className="animation-tiles">{nodeAnimations.map(item => <button key={item.id} className={cn(selected.animation === item.id && 'active')} onClick={() => setNodeAnimation(item.id)}><b>{item.glyph}</b><span>{prefs.locale === 'fr' ? item.fr : item.name}</span></button>)}</div></Section>
    </> : <div className="document-settings"><div className="document-icon"><Network size={24} /></div><h3>{prefs.locale === 'fr' ? 'Diagramme HTML sémantique' : 'Semantic HTML diagram'}</h3><p>{prefs.locale === 'fr' ? 'Chaque bloc est un composant DOM éditable. Seuls les connecteurs utilisent SVG pour rester nets à toute échelle.' : 'Every block is an editable DOM component. Only connectors use SVG so they remain crisp at any scale.'}</p><BackgroundThemePicker locale={prefs.locale} value={diagram.background} onChange={theme => { prefs.setTheme(theme); state.setDiagram(current => ({ ...current, background: theme })) }} /><Field label={prefs.locale === 'fr' ? 'Sous-titre' : 'Subtitle'}><textarea rows={3} value={diagram.subtitle} onChange={event => state.setDiagram(current => ({ ...current, subtitle: event.target.value }))} /></Field><div className="canvas-size"><Field label="Width"><input type="number" value={diagram.width} onChange={event => state.setDiagram(current => ({ ...current, width: Math.max(800, Number(event.target.value)) }))} /></Field><Field label="Height"><input type="number" value={diagram.height} onChange={event => state.setDiagram(current => ({ ...current, height: Math.max(500, Number(event.target.value)) }))} /></Field></div><button className="download-card" disabled={exporting} onClick={onDownload}>{exporting ? <LoaderCircle className="spin" size={18} /> : <Download size={18} />}<span><b>{prefs.locale === 'fr' ? 'Documents HTML + GIF' : 'HTML + GIF documents'}</b><small>{prefs.locale === 'fr' ? 'HTML autonome, puis son animation GIF' : 'Standalone HTML, then its animated GIF'}</small></span><Download size={15} /></button></div>}
  </div></aside>
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Section({ title, icon, open, onToggle, children }: { title: string; icon: ReactNode; open: boolean; onToggle: () => void; children: ReactNode }) { return <section className={cn('property-section', open && 'open')}><button className="section-trigger" onClick={onToggle}>{icon}<span>{title}</span><ChevronDown size={14} /></button>{open && <div className="section-content">{children}</div>}</section> }
function BackgroundThemePicker({ locale, value, onChange }: { locale: 'en' | 'fr'; value: AppTheme; onChange: (theme: AppTheme) => void }) { return <div className="background-themes"><span>{locale === 'fr' ? 'THÈME DU FOND' : 'BACKGROUND THEME'}</span><div>{themes.map(theme => <button key={theme.id} className={cn(`theme-${theme.id}`, value === theme.id && 'active')} onClick={() => onChange(theme.id)} title={locale === 'fr' ? theme.fr : theme.label}><i /><b>{locale === 'fr' ? theme.fr : theme.label}</b></button>)}</div><small>{locale === 'fr' ? 'Le thème choisi est conservé quand vous changez de modèle.' : 'Your chosen theme is preserved when switching templates.'}</small></div> }

function Canvas({ stageRef, diagram, selectedId, selectedEdgeId, onSelect, onSelectEdge, onConnect, onMove, onResize, zoom }: { stageRef: RefObject<HTMLDivElement | null>; diagram: Diagram; selectedId: string | null; selectedEdgeId: string | null; onSelect: (id: string | null) => void; onSelectEdge: (id: string | null) => void; onConnect: (from: string, to: string, fromSide: Side, toSide: Side) => void; onMove: (id: string, x: number, y: number) => void; onResize: (id: string, width: number, height: number) => void; zoom: number }) {
  const lookup = useMemo(() => Object.fromEntries(diagram.nodes.map(node => [node.id, node])), [diagram.nodes])
  const drag = useRef<{ kind: 'move' | 'resize'; node: DiagramNode; x: number; y: number; width: number; height: number } | null>(null)
  const [connecting, setConnecting] = useState<{ from: string; side: Side; x: number; y: number } | null>(null)
  const start = (event: PointerEvent<HTMLElement>, node: DiagramNode) => { event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); drag.current = { kind: 'move', node, x: event.clientX, y: event.clientY, width: nodeWidth(node), height: nodeHeight(node) }; onSelect(node.id) }
  const startResize = (event: PointerEvent<HTMLElement>, node: DiagramNode) => { event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); drag.current = { kind: 'resize', node, x: event.clientX, y: event.clientY, width: nodeWidth(node), height: nodeHeight(node) } }
  const pointerMove = (event: PointerEvent<HTMLDivElement>) => { if (drag.current) { const item = drag.current, dx = (event.clientX - item.x) / zoom, dy = (event.clientY - item.y) / zoom; if (item.kind === 'resize') onResize(item.node.id, Math.max(item.node.kind === 'group' ? 300 : 120, item.width + dx), Math.max(item.node.kind === 'group' ? 180 : 60, item.height + dy)); else onMove(item.node.id, Math.max(8, item.node.x + dx), Math.max(8, item.node.y + dy)) } if (connecting && stageRef.current) { const bounds = stageRef.current.getBoundingClientRect(); setConnecting(current => current ? { ...current, x: (event.clientX - bounds.left) / zoom, y: (event.clientY - bounds.top) / zoom } : null) } }
  const startConnection = (event: PointerEvent<HTMLButtonElement>, node: DiagramNode, side: Side) => { event.stopPropagation(); const point = endpoint(node, side); setConnecting({ from: node.id, side, x: point.x, y: point.y }) }
  const completeConnection = (event: PointerEvent<HTMLElement>, target: DiagramNode) => { if (!connecting || connecting.from === target.id) return; event.stopPropagation(); onConnect(connecting.from, target.id, connecting.side, sideAtPointer(event)); setConnecting(null) }
  const stop = () => { drag.current = null; setConnecting(null) }
  return <div className="diagram-viewport" onPointerMove={pointerMove} onPointerUp={stop} onPointerCancel={stop} onClick={() => { onSelect(null); onSelectEdge(null) }}><div className="stage-space" style={{ width: diagram.width * zoom, height: diagram.height * zoom }}><div ref={stageRef} className="diagram-stage" style={{ width: diagram.width, height: diagram.height, transform: `scale(${zoom})` }}>
    <svg className="edge-layer" viewBox={`0 0 ${diagram.width} ${diagram.height}`}><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8z" fill="context-stroke" /></marker><marker id="arrow-start" markerWidth="8" markerHeight="8" refX="1" refY="4" orient="auto"><path d="M8 0L0 4L8 8z" fill="context-stroke" /></marker></defs>{diagram.edges.map(edge => { const from = lookup[edge.from], to = lookup[edge.to]; if (!from || !to) return null; const d = edgePath(edge, from, to), center = edgeCenter(from, to); return <g key={edge.id} className={cn('diagram-edge', selectedEdgeId === edge.id && 'selected', edge.dashed && 'dashed')} style={{ color: edge.color }} onClick={event => { event.stopPropagation(); onSelectEdge(edge.id) }}><path className="edge-hitarea" d={d} /><path className="edge-track" d={d} /><path className={cn('edge-signal', edge.animation !== 'none' && `edge-motion-${edge.animation}`)} d={d} markerStart={edge.direction === 'both' ? 'url(#arrow-start)' : undefined} markerEnd="url(#arrow)" />{edge.label && <g className="edge-label" transform={`translate(${center.x} ${center.y})`}><rect x={-edge.label.length * 3.2 - 7} y={-10} width={edge.label.length * 6.4 + 14} height={20} rx={7} /><text textAnchor="middle" y="3.5">{edge.label}</text></g>}</g> })}{connecting && lookup[connecting.from] && <path className="edge-draft" d={draftPath(endpoint(lookup[connecting.from], connecting.side), connecting)} />}</svg>
    {diagram.nodes.map(node => <DiagramNodeView key={node.id} node={node} selected={selectedId === node.id} onPointerDown={start} onPointerUp={completeConnection} onResize={startResize} onConnect={startConnection} />)}
  </div></div></div>
}

function DiagramNodeView({ node, selected, onPointerDown, onPointerUp, onResize, onConnect }: { node: DiagramNode; selected: boolean; onPointerDown: (event: PointerEvent<HTMLElement>, node: DiagramNode) => void; onPointerUp: (event: PointerEvent<HTMLElement>, node: DiagramNode) => void; onResize: (event: PointerEvent<HTMLElement>, node: DiagramNode) => void; onConnect: (event: PointerEvent<HTMLButtonElement>, node: DiagramNode, side: Side) => void }) {
  const Icon = iconMap[node.icon ?? 'box'] ?? Box
  return <article className={cn('html-node', `kind-${node.kind}`, selected && 'selected')} style={{ left: node.x, top: node.y, width: nodeWidth(node), height: nodeHeight(node), '--node-tone': node.color, '--node-ink': node.textColor, zIndex: node.kind === 'group' ? 0 : 2 } as React.CSSProperties} onClick={event => event.stopPropagation()} onPointerDown={event => onPointerDown(event, node)} onPointerUp={event => onPointerUp(event, node)}>
    <div className="node-heading"><span className="node-icon">{node.kind === 'technology' && node.technology ? <BrandIcon technology={node.technology} size={26} /> : node.kind === 'electronic' && node.electronic ? <ElectronicIcon component={node.electronic} size={28} /> : <Icon size={node.kind === 'metric' ? 19 : 15} />}</span><div>{node.eyebrow && <em>{node.eyebrow}</em>}<h3>{node.title}</h3></div>{node.badge && <b>{node.badge}</b>}</div><p>{node.subtitle}</p>
    {node.items?.length ? <div className="node-items">{node.items.map(item => <span key={item}>{item}</span>)}</div> : null}
    {node.kind === 'platform' && <div className="platform-visual"><i /><i /><i /><i /><i /><i /></div>}{node.kind === 'database' && <div className="database-stack"><i /><i /><i /></div>}{node.kind === 'group' && <div className="group-grid" />}
    {(['top', 'right', 'bottom', 'left'] as Side[]).map(side => <button key={side} className={`node-port port-${side}`} onPointerDown={event => onConnect(event, node, side)} aria-label={`Connect ${side}`} />)}{selected && <i className="resize-handle" onPointerDown={event => onResize(event, node)} />}
  </article>
}

function BrandIcon({ technology, size = 22 }: { technology: string; size?: number }) { const item = getTechnology(technology); if (!item) return <Blocks size={size} />; const color = item.icon.hex === '000000' ? '#eef2f5' : `#${item.icon.hex}`; return <svg className="brand-icon" role="img" aria-label={item.name} width={size} height={size} viewBox="0 0 24 24" style={{ color }}><path fill="currentColor" d={item.icon.path} /></svg> }
function ElectronicIcon({ component, size = 22 }: { component: string; size?: number }) { const item = getElectronicComponent(component); if (!item) return <CircuitBoard size={size} />; return <svg className="electronic-icon" role="img" aria-label={item.name} width={size} height={size} viewBox="0 0 24 24" dangerouslySetInnerHTML={{ __html: item.svg }} /> }

function nodeWidth(node: DiagramNode) { return node.width ?? 190 }
function nodeHeight(node: DiagramNode) { return node.height ?? 100 }
function endpoint(node: DiagramNode, side: Side) { const width = nodeWidth(node), height = nodeHeight(node); return side === 'top' ? { x: node.x + width / 2, y: node.y } : side === 'bottom' ? { x: node.x + width / 2, y: node.y + height } : side === 'left' ? { x: node.x, y: node.y + height / 2 } : { x: node.x + width, y: node.y + height / 2 } }
function sideVector(side: Side) { return side === 'left' ? { x: -1, y: 0 } : side === 'right' ? { x: 1, y: 0 } : side === 'top' ? { x: 0, y: -1 } : { x: 0, y: 1 } }
function edgePath(edge: DiagramEdge, from: DiagramNode, to: DiagramNode) { const start = endpoint(from, edge.fromSide), end = endpoint(to, edge.toSide); if (edge.route === 'straight') return `M ${start.x} ${start.y} L ${end.x} ${end.y}`; if ((edge.route ?? 'curve') === 'curve') { const a = sideVector(edge.fromSide), b = sideVector(edge.toSide), distance = Math.max(70, Math.min(220, Math.hypot(end.x - start.x, end.y - start.y) * .38)); return `M ${start.x} ${start.y} C ${start.x + a.x * distance} ${start.y + a.y * distance}, ${end.x + b.x * distance} ${end.y + b.y * distance}, ${end.x} ${end.y}` } if ((edge.fromSide === 'left' || edge.fromSide === 'right') && (edge.toSide === 'left' || edge.toSide === 'right')) { const x = Math.round((start.x + end.x) / 2); return `M ${start.x} ${start.y} H ${x} V ${end.y} H ${end.x}` } const y = Math.round((start.y + end.y) / 2); return `M ${start.x} ${start.y} V ${y} H ${end.x} V ${end.y}` }
function edgeCenter(from: DiagramNode, to: DiagramNode) { return { x: (from.x + nodeWidth(from) / 2 + to.x + nodeWidth(to) / 2) / 2, y: (from.y + nodeHeight(from) / 2 + to.y + nodeHeight(to) / 2) / 2 } }
function draftPath(start: { x: number; y: number }, target: { x: number; y: number }) { return `M ${start.x} ${start.y} L ${target.x} ${target.y}` }
function sideAtPointer(event: PointerEvent<HTMLElement>): Side { const bounds = event.currentTarget.getBoundingClientRect(), x = event.clientX - bounds.left, y = event.clientY - bounds.top, horizontal = x / bounds.width, vertical = y / bounds.height; if (Math.min(horizontal, 1 - horizontal) < Math.min(vertical, 1 - vertical)) return horizontal < .5 ? 'left' : 'right'; return vertical < .5 ? 'top' : 'bottom' }
