import { type PointerEvent, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeftRight, ChevronDown, ClipboardPaste, Copy, Download, Link2, Palette, Play, Plus, Sparkles, Square, Trash2, Zap } from 'lucide-react'
import { useDiagram } from '../application/useDiagram'
import { arrowAnimations, nodeAnimations } from '../domain/animationCatalog'
import type { AppTheme, DiagramNode, Side } from '../domain/diagram'
import { usePreferences } from '../../preferences/application/usePreferences'
import { cn } from '../../../shared/lib/cn'
import { downloadDiagramGif } from '../../../shared/lib/gifExporter'

const colors = ['#f6c85f', '#ec7571', '#bc78c6', '#7a6fc8', '#2b9ea3', '#39ba84', '#2e74ca', '#232b42']
const themes: { id: AppTheme; label: string; fr: string }[] = [
  { id: 'midnight', label: 'Midnight', fr: 'Nuit' }, { id: 'blueprint', label: 'Blueprint', fr: 'Plan bleu' }, { id: 'electric', label: 'Electric', fr: 'Électrique' }, { id: 'light', label: 'Paper', fr: 'Papier' },
]

export function EditorPage() {
  const diagramState = useDiagram(), prefs = usePreferences()
  const { diagram, selected, selectedId, setSelectedId, selectedEdge, selectedEdgeId, setSelectedEdgeId, updateNode, updateEdge, removeSelectedEdge, removeSelectedNode, moveNode, resizeNode, addNode, copySelectedNode, pasteNode, canPaste, connect, arrowAnimation, setArrowAnimation, setNodeAnimation } = diagramState
  const [playing, setPlaying] = useState(false), [playKey, setPlayKey] = useState(0), [exporting, setExporting] = useState(false), [open, setOpen] = useState<Record<string, boolean>>({ step: true, node: false, arrows: false })
  const chooseNode = (id: string) => { setSelectedId(id) }
  const preview = () => { setPlaying(false); requestAnimationFrame(() => { setPlayKey(key => key + 1); setPlaying(true); window.setTimeout(() => setPlaying(false), 6500) }) }
  const changeTheme = (theme: AppTheme) => { prefs.setTheme(theme); diagramState.setDiagram(current => ({ ...current, background: theme })) }
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((!event.ctrlKey && !event.metaKey) || event.altKey || event.shiftKey || ['INPUT', 'TEXTAREA'].includes((event.target as HTMLElement)?.tagName)) return
      if (event.key.toLowerCase() === 'c' && selected) { event.preventDefault(); copySelectedNode() }
      if (event.key.toLowerCase() === 'v' && canPaste) { event.preventDefault(); pasteNode() }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [canPaste, copySelectedNode, pasteNode, selected])
  return <main className="app-shell dark-app" data-theme={prefs.theme}>
    <aside className="left-rail minimal-rail"><div className="brand"><span className="brand-dot">D</span></div><button className="avatar">CM</button></aside>
    <section className="workspace"><header className="topbar"><div className="crumbs"><span>{prefs.t.diagrams}</span><span className="slash">/</span><strong>{prefs.t.journey}</strong></div><div className="top-actions"><label className="theme-select"><Palette size={14} /><span>{prefs.t.theme}</span><select value={diagram.background} onChange={e => changeTheme(e.target.value as AppTheme)}>{themes.map(theme => <option key={theme.id} value={theme.id}>{prefs.locale === 'fr' ? theme.fr : theme.label}</option>)}</select></label><label className="language-switch"><select aria-label={prefs.t.language} value={prefs.locale} onChange={e => prefs.setLocale(e.target.value as 'en' | 'fr')}><option value="en">EN</option><option value="fr">FR</option></select></label><button className="export-button" onClick={() => setExporting(true)}><Download size={16} /> {prefs.t.export}</button></div></header>
      <div className="editor-area"><section className="canvas-panel" data-canvas-theme={diagram.background}>
        <div className="canvas-toolbar refined-toolbar"><button className={cn('tool-button', open.node && 'selected')} onClick={() => setOpen(current => ({ ...current, node: !current.node }))} title={prefs.t.animation}><Sparkles size={17} /></button><span className="toolbar-separator" /><button className="tool-button" onClick={addNode} title={prefs.t.addBlock}><Plus size={18} /></button></div>
        <Canvas nodes={diagram.nodes} edges={diagram.edges} selectedId={selectedId} selectedEdgeId={selectedEdgeId} onSelect={chooseNode} onSelectEdge={setSelectedEdgeId} onConnect={connect} onMove={moveNode} onResize={resizeNode} playing={playing} playKey={playKey} canDrag />
        <div className="canvas-status"><span className="autosave"><i /> {prefs.t.saved}</span></div>
      </section>
      <aside className="inspector"><div className="inspector-heading"><span>{selectedEdge ? prefs.t.link : prefs.t.properties}</span>{(selected || selectedEdge) && <div className="inspector-actions">{selected && <><button className="tiny-icon" onClick={copySelectedNode} title={prefs.t.copy}><Copy size={16} /></button><button className="tiny-icon" disabled={!canPaste} onClick={pasteNode} title={prefs.t.paste}><ClipboardPaste size={16} /></button></>}<button className="tiny-icon" onClick={() => selectedEdge ? removeSelectedEdge() : removeSelectedNode()} title={prefs.t.delete}><Trash2 size={16} /></button></div>}</div><div className="inspector-content">
        {selectedEdge ? <><Accordion title={prefs.t.link} icon={<Link2 size={14} />} open={open.step} onToggle={() => setOpen(current => ({ ...current, step: !current.step }))}><p className="inspector-kicker">{selectedEdge.from} → {selectedEdge.to}</p><Field label={prefs.t.linkColor}><input type="color" className="edge-color" value={selectedEdge.color} onChange={event => updateEdge({ color: event.target.value })} /></Field><button className="direction-toggle" onClick={() => updateEdge({ direction: selectedEdge.direction === 'forward' ? 'both' : 'forward' })}><ArrowLeftRight size={15} /> {selectedEdge.direction === 'both' ? '↔' : '→'}</button></Accordion><ArrowAnimationEditor panelOpen={open.arrows} setOpen={setOpen} prefs={prefs} arrowAnimation={arrowAnimation} setArrowAnimation={setArrowAnimation} /></> : selected ? <>
        <Accordion title={prefs.t.properties} icon={<Square size={14} />} open={open.step} onToggle={() => setOpen(current => ({ ...current, step: !current.step }))}><p className="inspector-kicker">{prefs.t.selectedStep}</p><Field label={prefs.t.title}><input value={selected.title} onChange={e => updateNode({ title: e.target.value })} /></Field><Field label={prefs.t.description}><textarea rows={2} value={selected.subtitle} onChange={e => updateNode({ subtitle: e.target.value })} /></Field><Field label={prefs.t.color}><div className="swatches">{colors.map(color => <button key={color} className={cn('swatch', selected.color === color && 'current')} style={{ background: color }} onClick={() => updateNode({ color })} />)}</div></Field></Accordion>
        <Accordion title={prefs.t.animation} icon={<Sparkles size={14} />} open={open.node} onToggle={() => setOpen(current => ({ ...current, node: !current.node }))}><div className="animation-grid flat-animation-grid">{nodeAnimations.map(item => <button key={item.id} className={cn('animation-card', selected.animation === item.id && 'active')} onClick={() => setNodeAnimation(item.id)}><b>{item.glyph}</b><span>{prefs.locale === 'fr' ? item.fr : item.name}<small>{prefs.locale === 'fr' ? item.frDescription : item.description}</small></span></button>)}</div></Accordion>
        <ArrowAnimationEditor panelOpen={open.arrows} setOpen={setOpen} prefs={prefs} arrowAnimation={arrowAnimation} setArrowAnimation={setArrowAnimation} /></> : <div className="empty-inspector"><Square size={26} /><b>{prefs.locale === 'fr' ? 'Commencez par créer un bloc' : 'Start by creating a block'}</b><small>{prefs.locale === 'fr' ? 'Ajoutez un bloc depuis la barre à gauche.' : 'Add a block from the toolbar.'}</small><button className="create" onClick={addNode}><Plus size={15} /> {prefs.t.addBlock}</button></div>}
      </div><div className="preview-box"><div><Play size={17} /><span><b>{prefs.t.preview}</b><small>{prefs.t.previewHint}</small></span></div><button onClick={preview}><Play size={14} fill="currentColor" /></button></div></aside></div>
    </section>{exporting && <ExportNotice nodes={diagram.nodes} edges={diagram.edges} text={prefs.t} onClose={() => setExporting(false)} />}</main>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Accordion({ title, icon, open, onToggle, nested = false, children }: { title: string; icon?: React.ReactNode; open: boolean; onToggle: () => void; nested?: boolean; children: React.ReactNode }) { return <section className={cn('accordion', nested && 'nested', open && 'open')}><button className="accordion-trigger" onClick={onToggle}>{icon}<span>{title}</span><ChevronDown size={15} /></button>{open && <div className="accordion-content">{children}</div>}</section> }
function ArrowAnimationEditor({ panelOpen, setOpen, prefs, arrowAnimation, setArrowAnimation }: { panelOpen: boolean; setOpen: React.Dispatch<React.SetStateAction<Record<string, boolean>>>; prefs: ReturnType<typeof usePreferences>; arrowAnimation: string; setArrowAnimation: (animation: string) => void }) { return <Accordion title={prefs.t.arrowAnimations} icon={<Zap size={14} />} open={panelOpen} onToggle={() => setOpen(current => ({ ...current, arrows: !current.arrows }))}><div className="arrow-list flat-arrow-list">{arrowAnimations.map(item => <button key={item.id} className={cn(arrowAnimation === item.id && 'active')} onClick={() => setArrowAnimation(item.id)}><span className={`arrow-sample arrow-${item.id}`} /> <span><b>{prefs.locale === 'fr' ? item.fr : item.name}</b><small>{prefs.locale === 'fr' ? item.frDescription : item.description}</small></span></button>)}</div></Accordion> }
function Canvas({ nodes, edges, selectedId, selectedEdgeId, onSelect, onSelectEdge, onConnect, onMove, onResize, playing, playKey, canDrag }: { nodes: DiagramNode[]; edges: import('../domain/diagram').DiagramEdge[]; selectedId: string | null; selectedEdgeId: string | null; onSelect: (id: string) => void; onSelectEdge: (id: string) => void; onConnect: (from: string, to: string, fromSide: Side, toSide: Side) => void; onMove: (id: string, x: number, y: number) => void; onResize: (id: string, width: number, height: number) => void; playing: boolean; playKey: number; canDrag: boolean }) {
  const drag = useRef<{ kind: 'move' | 'resize'; node: DiagramNode; x: number; y: number; width?: number; height?: number } | null>(null), lookup = useMemo(() => Object.fromEntries(nodes.map(node => [node.id, node])), [nodes])
  const stageRef = useRef<HTMLDivElement>(null)
  const [connecting, setConnecting] = useState<{ from: string; side: Side; x: number; y: number } | null>(null)
  const start = (event: PointerEvent<HTMLDivElement>, node: DiagramNode) => { if (!canDrag) return; event.currentTarget.setPointerCapture(event.pointerId); drag.current = { kind: 'move', node, x: event.clientX, y: event.clientY } }
  const startResize = (event: PointerEvent<HTMLElement>, node: DiagramNode) => { event.stopPropagation(); drag.current = { kind: 'resize', node, x: event.clientX, y: event.clientY, width: nodeWidth(node), height: nodeHeight(node) } }
  const move = (event: PointerEvent<HTMLDivElement>) => { if (!drag.current) return; const { node, x, y } = drag.current; if (drag.current.kind === 'resize') { onResize(node.id, Math.max(130, (drag.current.width ?? 166) + event.clientX - x), Math.max(82, (drag.current.height ?? 110) + event.clientY - y)); return } onMove(node.id, Math.max(16, node.x + event.clientX - x), Math.max(16, node.y + event.clientY - y)) }
  const followConnection = (event: PointerEvent<HTMLDivElement>) => { move(event); if (!connecting || !stageRef.current) return; const bounds = stageRef.current.getBoundingClientRect(); setConnecting(current => current ? { ...current, x: event.clientX - bounds.left, y: event.clientY - bounds.top } : null) }
  const startConnection = (event: PointerEvent<HTMLButtonElement>, node: DiagramNode, side: Side) => { event.stopPropagation(); const point = endpoint(node, side); setConnecting({ from: node.id, side, x: point.x, y: point.y }) }
  const completeConnection = (event: PointerEvent<HTMLDivElement>, target: DiagramNode) => { if (!connecting || connecting.from === target.id) return; event.stopPropagation(); onConnect(connecting.from, target.id, connecting.side, sideAtPointer(event, target)); setConnecting(null) }
  return <div className="diagram-viewport" onPointerMove={followConnection} onPointerUp={() => { drag.current = null; setConnecting(null) }}><div ref={stageRef} className="diagram-stage"><svg className="edge-layer" viewBox="0 0 920 620"><defs><marker id="arrow" markerWidth="9" markerHeight="9" refX="7" refY="4" orient="auto"><path d="M0,0 L0,8 L8,4 z" fill="currentColor" /></marker><marker id="arrow-start" markerWidth="9" markerHeight="9" refX="1" refY="4" orient="auto"><path d="M8,0 L8,8 L0,4 z" fill="currentColor" /></marker></defs>{edges.map(edge => { const from = lookup[edge.from], to = lookup[edge.to]; if (!from || !to) return null; const path = orthogonalPath(endpoint(from, edge.fromSide), endpoint(to, edge.toSide), edge.fromSide, edge.toSide), isSelected = selectedEdgeId === edge.id; return <g key={edge.id} style={{ color: edge.color }} className={cn('diagram-edge', isSelected && 'selected')} onClick={event => { event.stopPropagation(); onSelectEdge(edge.id) }}><path className="edge-hitarea" d={path} /><path className="edge-track" d={path} /><path className={`edge-flowline edge-motion-${edge.animation}`} d={path} markerStart={edge.direction === 'both' ? 'url(#arrow-start)' : undefined} markerEnd="url(#arrow)" /></g> })}{connecting && <path className="edge-draft" d={draftPath(endpoint(lookup[connecting.from], connecting.side), connecting)} />}</svg>{nodes.map(node => <div key={`${node.id}-${playKey}`} className={cn('diagram-node', selectedId === node.id && playing && `motion-${node.animation}`)} style={{ left: node.x, top: node.y, width: nodeWidth(node), height: nodeHeight(node), color: node.textColor, background: node.color }} onClick={() => onSelect(node.id)} onPointerDown={event => start(event, node)} onPointerUp={event => completeConnection(event, node)}><span className="node-copy"><b>{node.title}</b><small>{node.subtitle}</small></span>{(['top','right','bottom','left'] as Side[]).map(side => <button key={side} className={`node-port port-${side}`} onPointerDown={event => startConnection(event, node, side)} aria-label={`Connect ${side}`} />)}{selectedId === node.id && <i className="resize-handle" onPointerDown={event => startResize(event, node)} />}</div>)}</div></div>
}

function nodeWidth(node: DiagramNode) { return node.width ?? 166 }
function nodeHeight(node: DiagramNode) { return node.height ?? 110 }
function endpoint(node: DiagramNode, side: Side) { const width = nodeWidth(node), height = nodeHeight(node); if (side === 'top') return { x: node.x + width / 2, y: node.y - 1 }; if (side === 'bottom') return { x: node.x + width / 2, y: node.y + height + 1 }; if (side === 'left') return { x: node.x - 1, y: node.y + height / 2 }; return { x: node.x + width + 1, y: node.y + height / 2 } }
function orthogonalPath(start: { x: number; y: number }, end: { x: number; y: number }, fromSide: Side, toSide: Side) { if ((fromSide === 'left' || fromSide === 'right') && (toSide === 'left' || toSide === 'right')) { const x = Math.round((start.x + end.x) / 2); return `M ${start.x} ${start.y} H ${x} V ${end.y} H ${end.x}` } if ((fromSide === 'top' || fromSide === 'bottom') && (toSide === 'top' || toSide === 'bottom')) { const y = Math.round((start.y + end.y) / 2); return `M ${start.x} ${start.y} V ${y} H ${end.x} V ${end.y}` } return fromSide === 'left' || fromSide === 'right' ? `M ${start.x} ${start.y} H ${end.x} V ${end.y}` : `M ${start.x} ${start.y} V ${end.y} H ${end.x}` }
function draftPath(start: { x: number; y: number }, target: { side: Side; x: number; y: number }) { return target.side === 'left' || target.side === 'right' ? `M ${start.x} ${start.y} H ${target.x} V ${target.y}` : `M ${start.x} ${start.y} V ${target.y} H ${target.x}` }
function sideAtPointer(event: PointerEvent<HTMLDivElement>, node: DiagramNode): Side { const bounds = event.currentTarget.getBoundingClientRect(), x = event.clientX - bounds.left, y = event.clientY - bounds.top, horizontal = x / bounds.width, vertical = y / bounds.height; if (Math.min(horizontal, 1 - horizontal) < Math.min(vertical, 1 - vertical)) return horizontal < .5 ? 'left' : 'right'; return vertical < .5 ? 'top' : 'bottom' }
function ExportNotice({ nodes, edges, text, onClose }: { nodes: DiagramNode[]; edges: import('../domain/diagram').DiagramEdge[]; text: ReturnType<typeof usePreferences>['t']; onClose: () => void }) { const [creating, setCreating] = useState(false); const exportGif = async () => { setCreating(true); await downloadDiagramGif(nodes, edges); onClose() }; return <div className="modal-backdrop"><div className="export-dialog"><span className="eyebrow">{text.gif}</span><h2>{text.ready}</h2><p>{text.exportDescription}</p><div className="modal-actions"><button className="cancel" disabled={creating} onClick={onClose}>{text.cancel}</button><button className="create" disabled={creating} onClick={exportGif}><Download size={16} /> {creating ? '…' : text.create}</button></div></div></div> }
