import { type ChangeEvent, type PointerEvent, useMemo, useRef, useState } from 'react'
import { ChevronDown, Download, ImagePlus, Link2, Palette, Play, Plus, Sparkles, Square, Trash2, Upload, Zap } from 'lucide-react'
import { useDiagram } from '../application/useDiagram'
import { arrowAnimations, categoryLabels, nodeAnimations } from '../domain/animationCatalog'
import type { AppTheme, DiagramNode } from '../domain/diagram'
import { usePreferences } from '../../preferences/application/usePreferences'
import { cn } from '../../../shared/lib/cn'
import { downloadDiagramGif } from '../../../shared/lib/gifExporter'

const colors = ['#f6c85f', '#ec7571', '#bc78c6', '#7a6fc8', '#2b9ea3', '#39ba84', '#2e74ca', '#232b42']
const themes: { id: AppTheme; label: string; fr: string }[] = [
  { id: 'midnight', label: 'Midnight', fr: 'Nuit' }, { id: 'blueprint', label: 'Blueprint', fr: 'Plan bleu' }, { id: 'electric', label: 'Electric', fr: 'Électrique' }, { id: 'light', label: 'Paper', fr: 'Papier' },
]

export function EditorPage() {
  const diagramState = useDiagram(), prefs = usePreferences()
  const { diagram, selected, selectedId, setSelectedId, selectedEdge, selectedEdgeId, setSelectedEdgeId, updateNode, updateEdge, removeSelectedEdge, moveNode, addNode, addImageToNode, connect, arrowAnimation, setArrowAnimation, setNodeAnimation } = diagramState
  const [tool, setTool] = useState<'select' | 'link'>('select'), [linkStart, setLinkStart] = useState<string | null>(null), [playing, setPlaying] = useState(false), [playKey, setPlayKey] = useState(0), [exporting, setExporting] = useState(false), [open, setOpen] = useState<Record<string, boolean>>({ step: true, node: false, arrows: false })
  const fileRef = useRef<HTMLInputElement>(null)
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => addImageToNode(String(reader.result)); reader.readAsDataURL(file); event.target.value = '' }
  const chooseNode = (id: string) => { if (tool !== 'link') { setSelectedId(id); return }; if (!linkStart) { setLinkStart(id); setSelectedId(id) } else if (linkStart !== id) { connect(linkStart, id); setSelectedId(id) } }
  const preview = () => { setPlaying(false); requestAnimationFrame(() => { setPlayKey(key => key + 1); setPlaying(true); window.setTimeout(() => setPlaying(false), 5100) }) }
  const changeTheme = (theme: AppTheme) => { prefs.setTheme(theme); diagramState.setDiagram(current => ({ ...current, background: theme })) }
  return <main className="app-shell dark-app" data-theme={prefs.theme}>
    <aside className="left-rail minimal-rail"><div className="brand"><span className="brand-dot">D</span></div><button className="avatar">CM</button></aside>
    <section className="workspace"><header className="topbar"><div className="crumbs"><span>{prefs.t.diagrams}</span><span className="slash">/</span><strong>{prefs.t.journey}</strong></div><div className="top-actions"><label className="theme-select"><Palette size={14} /><span>{prefs.t.theme}</span><select value={diagram.background} onChange={e => changeTheme(e.target.value as AppTheme)}>{themes.map(theme => <option key={theme.id} value={theme.id}>{prefs.locale === 'fr' ? theme.fr : theme.label}</option>)}</select></label><label className="language-switch"><select aria-label={prefs.t.language} value={prefs.locale} onChange={e => prefs.setLocale(e.target.value as 'en' | 'fr')}><option value="en">EN</option><option value="fr">FR</option></select></label><button className="export-button" onClick={() => setExporting(true)}><Download size={16} /> {prefs.t.export}</button></div></header>
      <div className="editor-area"><section className="canvas-panel" data-canvas-theme={diagram.background}>
        <div className="canvas-toolbar refined-toolbar"><button className={cn('tool-button', tool === 'link' && 'selected')} onClick={() => { setTool('link'); setLinkStart(null) }} title="Start a new link"><Link2 size={17} /></button><button className={cn('tool-button', open.node && 'selected')} onClick={() => setOpen(current => ({ ...current, node: !current.node }))} title={prefs.t.animation}><Sparkles size={17} /></button><span className="toolbar-separator" /><button className="tool-button" onClick={() => { addNode(); setTool('select'); setLinkStart(null) }} title="Add step"><Plus size={18} /></button><button className="tool-button" onClick={() => fileRef.current?.click()} title={prefs.t.addImage}><ImagePlus size={18} /></button><input ref={fileRef} className="hidden" type="file" accept="image/*" onChange={upload} /></div>
        {tool === 'link' && <div className="link-hint">{linkStart ? prefs.t.linkTo : prefs.t.linkFrom}</div>}
        <Canvas nodes={diagram.nodes} edges={diagram.edges} selectedId={selectedId} linkStart={linkStart} selectedEdgeId={selectedEdgeId} onSelect={chooseNode} onSelectEdge={setSelectedEdgeId} onMove={moveNode} playing={playing} playKey={playKey} canDrag={tool === 'select'} />
        <div className="canvas-status"><span className="autosave"><i /> {prefs.t.saved}</span></div>
      </section>
      <aside className="inspector"><div className="inspector-heading"><span>{selectedEdge ? prefs.t.link : prefs.t.properties}</span><button className="tiny-icon" onClick={() => selectedEdge ? removeSelectedEdge() : updateNode({ image: undefined, kind: 'block' })} title={selectedEdge ? prefs.t.deleteLink : prefs.t.removeImage}><Trash2 size={16} /></button></div><div className="inspector-content">
        {selectedEdge ? <><Accordion title={prefs.t.link} icon={<Link2 size={14} />} open={open.step} onToggle={() => setOpen(current => ({ ...current, step: !current.step }))}><p className="inspector-kicker">{selectedEdge.from} → {selectedEdge.to}</p><Field label={prefs.t.linkColor}><input type="color" className="edge-color" value={selectedEdge.color} onChange={event => updateEdge({ color: event.target.value })} /></Field></Accordion><ArrowAnimationEditor panelOpen={open.arrows} sections={open} setOpen={setOpen} prefs={prefs} arrowAnimation={arrowAnimation} setArrowAnimation={setArrowAnimation} /></> : <>
        <Accordion title={prefs.t.properties} icon={<Square size={14} />} open={open.step} onToggle={() => setOpen(current => ({ ...current, step: !current.step }))}><p className="inspector-kicker">{selected.image ? prefs.t.imageStep : prefs.t.selectedStep}</p><Field label={prefs.t.title}><input value={selected.title} onChange={e => updateNode({ title: e.target.value })} /></Field><Field label={prefs.t.description}><textarea rows={2} value={selected.subtitle} onChange={e => updateNode({ subtitle: e.target.value })} /></Field><Field label={prefs.t.color}><div className="swatches">{colors.map(color => <button key={color} className={cn('swatch', selected.color === color && 'current')} style={{ background: color }} onClick={() => updateNode({ color })} />)}</div></Field><button className="replace-image" onClick={() => fileRef.current?.click()}><Upload size={14} /> {selected.image ? prefs.t.replaceImage : prefs.t.addImage}</button></Accordion>
        <Accordion title={prefs.t.animation} icon={<Sparkles size={14} />} open={open.node} onToggle={() => setOpen(current => ({ ...current, node: !current.node }))}>{(['entrance','emphasis','technical','construction','electrical'] as const).map(category => <Accordion key={category} nested title={categoryLabels[category][prefs.locale]} open={open[`node-${category}`] ?? false} onToggle={() => setOpen(current => ({ ...current, [`node-${category}`]: !current[`node-${category}`] }))}><div className="animation-grid">{nodeAnimations.filter(item => item.category === category).map(item => <button key={item.id} className={cn('animation-card', selected.animation === item.id && 'active')} onClick={() => setNodeAnimation(item.id)}><b>{item.glyph}</b><span>{prefs.locale === 'fr' ? item.fr : item.name}<small>{prefs.locale === 'fr' ? item.frDescription : item.description}</small></span></button>)}</div></Accordion>)}<Field label={`${prefs.t.delay} · ${selected.delay} ms`}><input className="range" type="range" min="0" max="2200" step="100" value={selected.delay} onChange={e => updateNode({ delay: Number(e.target.value) })} /></Field></Accordion>
        <ArrowAnimationEditor panelOpen={open.arrows} sections={open} setOpen={setOpen} prefs={prefs} arrowAnimation={arrowAnimation} setArrowAnimation={setArrowAnimation} /></>}
      </div><div className="preview-box"><div><Play size={17} /><span><b>{prefs.t.preview}</b><small>{prefs.t.previewHint}</small></span></div><button onClick={preview}><Play size={14} fill="currentColor" /></button></div></aside></div>
    </section>{exporting && <ExportNotice nodes={diagram.nodes} edges={diagram.edges} text={prefs.t} onClose={() => setExporting(false)} />}</main>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Accordion({ title, icon, open, onToggle, nested = false, children }: { title: string; icon?: React.ReactNode; open: boolean; onToggle: () => void; nested?: boolean; children: React.ReactNode }) { return <section className={cn('accordion', nested && 'nested', open && 'open')}><button className="accordion-trigger" onClick={onToggle}>{icon}<span>{title}</span><ChevronDown size={15} /></button>{open && <div className="accordion-content">{children}</div>}</section> }
function ArrowAnimationEditor({ panelOpen, sections, setOpen, prefs, arrowAnimation, setArrowAnimation }: { panelOpen: boolean; sections: Record<string, boolean>; setOpen: React.Dispatch<React.SetStateAction<Record<string, boolean>>>; prefs: ReturnType<typeof usePreferences>; arrowAnimation: string; setArrowAnimation: (animation: string) => void }) { return <Accordion title={prefs.t.arrowAnimations} icon={<Zap size={14} />} open={panelOpen} onToggle={() => setOpen(current => ({ ...current, arrows: !current.arrows }))}>{(['software','construction','electrical'] as const).map(category => <Accordion key={category} nested title={prefs.t[category]} open={sections[`arrow-${category}`] ?? false} onToggle={() => setOpen(current => ({ ...current, [`arrow-${category}`]: !current[`arrow-${category}`] }))}><div className="arrow-list">{arrowAnimations.filter(item => item.category === category).map(item => <button key={item.id} className={cn(arrowAnimation === item.id && 'active')} onClick={() => setArrowAnimation(item.id)}><span className={`arrow-sample arrow-${item.id}`} /> <span><b>{prefs.locale === 'fr' ? item.fr : item.name}</b><small>{prefs.locale === 'fr' ? item.frDescription : item.description}</small></span></button>)}</div></Accordion>)}</Accordion> }
function Canvas({ nodes, edges, selectedId, linkStart, selectedEdgeId, onSelect, onSelectEdge, onMove, playing, playKey, canDrag }: { nodes: DiagramNode[]; edges: { id: string; from: string; to: string; animation: string; color: string }[]; selectedId: string; linkStart: string | null; selectedEdgeId: string | null; onSelect: (id: string) => void; onSelectEdge: (id: string) => void; onMove: (id: string, x: number, y: number) => void; playing: boolean; playKey: number; canDrag: boolean }) {
  const drag = useRef<{ node: DiagramNode; x: number; y: number } | null>(null), lookup = useMemo(() => Object.fromEntries(nodes.map(node => [node.id, node])), [nodes])
  const start = (event: PointerEvent<HTMLDivElement>, node: DiagramNode) => { if (!canDrag) return; event.currentTarget.setPointerCapture(event.pointerId); drag.current = { node, x: event.clientX, y: event.clientY } }
  const move = (event: PointerEvent<HTMLDivElement>) => { if (!drag.current) return; const { node, x, y } = drag.current; onMove(node.id, Math.max(16, node.x + event.clientX - x), Math.max(16, node.y + event.clientY - y)) }
  return <div className="diagram-viewport" onPointerMove={move} onPointerUp={() => { drag.current = null }}><div className="diagram-stage"><svg className="edge-layer" viewBox="0 0 920 620"><defs><marker id="arrow" markerWidth="9" markerHeight="9" refX="7" refY="4" orient="auto"><path d="M0,0 L0,8 L8,4 z" fill="currentColor" /></marker></defs>{edges.map(edge => { const from = lookup[edge.from], to = lookup[edge.to]; if (!from || !to) return null; const middle = Math.round((from.x + to.x + 158) / 2), path = `M ${from.x + 166} ${from.y + 55} H ${middle} V ${to.y + 55} H ${to.x - 10}`, isSelected = selectedEdgeId === edge.id; return <g key={edge.id} style={{ color: edge.color }} className={cn('diagram-edge', isSelected && 'selected')} onClick={event => { event.stopPropagation(); onSelectEdge(edge.id) }}><path className="edge-hitarea" d={path} /><path className="edge-track" d={path} /><path className={`edge-flowline edge-motion-${edge.animation}`} d={path} markerEnd="url(#arrow)" /></g> })}</svg>{nodes.map(node => <div key={`${node.id}-${playKey}`} className={cn('diagram-node', selectedId === node.id && 'selected', linkStart === node.id && 'link-source', node.image && 'has-step-image', playing && `motion-${node.animation}`)} style={{ left: node.x, top: node.y, color: node.textColor, background: node.image ? `linear-gradient(90deg, ${node.color}, ${node.color}cc)` : node.color, animationDelay: `${node.delay}ms` }} onClick={() => onSelect(node.id)} onPointerDown={event => start(event, node)}>{node.image && <img src={node.image} alt="" />}<span className="node-copy"><b>{node.title}</b><small>{node.subtitle}</small></span>{selectedId === node.id && <i className="resize-handle" />}</div>)}</div></div>
}
function ExportNotice({ nodes, edges, text, onClose }: { nodes: DiagramNode[]; edges: import('../domain/diagram').DiagramEdge[]; text: ReturnType<typeof usePreferences>['t']; onClose: () => void }) { const [creating, setCreating] = useState(false); const exportGif = async () => { setCreating(true); await downloadDiagramGif(nodes, edges); onClose() }; return <div className="modal-backdrop"><div className="export-dialog"><span className="eyebrow">{text.gif}</span><h2>{text.ready}</h2><p>{text.exportDescription}</p><div className="modal-actions"><button className="cancel" disabled={creating} onClick={onClose}>{text.cancel}</button><button className="create" disabled={creating} onClick={exportGif}><Download size={16} /> {creating ? '…' : text.create}</button></div></div></div> }
